### PR TITLE
Added numbering for criteria

### PR DESCRIPTION
**Pull request by jandrieu**
Set up with canonical URIs: https://www.w3.org/TR/did-rubric#criteria-XXX

***
<a href="https://pr-preview.s3.amazonaws.com/LegReq/did-rubric/pull/28.html" title="Last updated on Aug 17, 2021, 5:34 AM UTC (09d6319)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-rubric/28/eb1d8f7...LegReq:09d6319.html" title="Last updated on Aug 17, 2021, 5:34 AM UTC (09d6319)">Diff</a>

### CODE REVIEW

**Comment by jandrieu** [comment]
This should be merged after #27

**Review by dhh1128 — CHANGES_REQUESTED** [review]
The ID of an individual criterion should probably be "criterion-1", not "criteria-1". Alternatively, we could abbreviate as "cr-1" or "crit-1".

The diff on this PR should be two lines per inserted ID * the number of criteria -- not thousands of lines?

**Comment by jandrieu** [comment]
I concur that formally, "criterion" is the correct grammar, however, I find that term never roles of the tongue and have, in my own conversations, shifted to use criteria for both singular and plural. Almost no one I know correctly uses "criterion", although both "incorrect" uses are common (people using criteria for singular and people using criterion for plural).

I think more resonant is I believe people are going to refer to, say, the 23rd criterion as "criteria 23" far more often than they will say "criterion 23". 

Sure I can't talk you into that usage?

As for the # of lines in the PR. The problem is that somewhere early in the edit, the diff tracking got out of sync, so there is a bunch of text that is only "updated" because it got shifted by a bit. Take a gander and see if I'm not misinterpreting what's going on.

(If something seems amiss, I'll figure out a way to get a cleaner update.)

**Comment by jandrieu** [comment]
I added a section in the introduction explaining the rational for criteria v criterion.

If Nixon could say "let me now return to the third criteria", I think its fair game for us to use the simpler, more common "criteria" for both singular and plural.

**Review by dhh1128 — APPROVED** [review]

**Pull request merged**
