### PR TITLE
Add links to external evaluation and conference paper.

### PR DESCRIPTION
**Pull request by peacekeeper**
Addresses https://github.com/w3c/did-rubric/issues/45.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-rubric/pull/47.html" title="Last updated on Aug 25, 2021, 8:27 PM UTC (b39b54c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-rubric/47/3342ea1...b39b54c.html" title="Last updated on Aug 25, 2021, 8:27 PM UTC (b39b54c)">Diff</a>

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
@jandrieu @dhh1128 can you please review this PR?

**Comment by OR13** [comment]
based on the call today, I suggest moving these sections to the rubric.

Similar to:

https://github.com/w3c/did-imp-guide/pull/29

**Comment by peacekeeper** [comment]
> I suggest moving these sections to the rubric.

This is the Rubric. Do you mean moving to the Implementation Guide?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-09-21-did#section5-2) on 2021-09-21

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. Add links to external evaluation and conference paper. (pr did-rubric#47)

_See github pull request [did-rubric#47](https://github.com/w3c/did-rubric/pull/47)._




**Joe Andrieu:** Let's talk about #47 - the chairs have an opinion but want to include the rest of the group - adds a reference to external publications - Daniel and I would like to avoid the rubric becoming an index  
… draw the line by citation to only papers mentioned in a criteria  

**Ryan Grant:** I have trouble understanding  

**Joe Andrieu:** All of the criteria need an evaluation. If the cited evaluation is from a published report, then point to author, when, and who paid.  
… the other was about including part of an evaluation in the rubric. Not opposed to citing where the criteria came from.  

**Orie Steele:** Agree with Joe. The rubric has a specific format and don't turn it to an index. Link to independent respects somewhere like we did with the SRI evaluation in the IG.  

**Joe Andrieu:** That sounds great - to put it in the Implementation Guide.  

**Daniel Burnett:** OK on time Joe?  

</details>

**Comment by jandrieu** [comment]
@peacekeeper Yes, I believe @OR13 did mean moving it to the implementation guide.

I think that's a good option.

We'd still love to get any new or updated criteria from the SBA Research work into the registry. That would earn it a place in the Rubric itself, if that's worth the effort.

We're just trying to hone the core of the rubric as registry to be fundamentally a set of vetted criteria rather than direct guidance on what "objectively" matters in a DID method. In other words, the rubric is about helping people ask the right questions rather than presenting the "best" answers or open ended discussion. We're now in clean up mode to get the current content aligned with the new registration process.

Would that work for you Markus?

**Comment by OR13** [comment]
@peacekeeper sorry... yes, on the call there was agreement the imp guide could host these links, like we do for the SRI links.

**Comment by jandrieu** [comment]
@peacekeeper Looks like the PR for the implementation guide was merged.

Are we good to close?

**Comment by jandrieu** [comment]
Issue resolved. No objection to closing.

Closing.

**Pull request closed without merging**
